# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import os
from PyQt6 import QtCore, QtGui, QtWidgets
import hashlib
import random
import tkinter as tk
from tkinter import messagebox
root = tk.Tk()
root.withdraw()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 721)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color:rgb(200, 211, 212)")
        MainWindow.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Vietnamese, QtCore.QLocale.Country.Vietnam))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.centralwidget.setFont(font)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("background-color:rgb(234, 250, 255)")
        self.centralwidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Vietnamese, QtCore.QLocale.Country.Vietnam))
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 1131, 701))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("background-color:rgb(200, 211, 212)")
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Vietnamese, QtCore.QLocale.Country.Vietnam))
        self.tabWidget.setObjectName("tabWidget")
        self.taoKhoa = QtWidgets.QWidget()
        self.taoKhoa.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Vietnamese, QtCore.QLocale.Country.Vietnam))
        self.taoKhoa.setObjectName("taoKhoa")
        self.groupBox = QtWidgets.QGroupBox(parent=self.taoKhoa)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 1091, 661))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setStyleSheet("background-color:rgb(200, 211, 212)")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 180, 921, 331))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=self.groupBox_3)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 60, 401, 231))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(70, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(270, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.oE1 = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.oE1.setGeometry(QtCore.QRect(20, 110, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oE1.setFont(font)
        self.oE1.setObjectName("oE1")
        self.oN1 = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.oN1.setGeometry(QtCore.QRect(220, 110, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oN1.setFont(font)
        self.oN1.setObjectName("oN1")
        self.groupBox_5 = QtWidgets.QGroupBox(parent=self.groupBox_3)
        self.groupBox_5.setGeometry(QtCore.QRect(490, 60, 411, 231))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_5.setGeometry(QtCore.QRect(80, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(280, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.oD = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.oD.setGeometry(QtCore.QRect(30, 110, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oD.setFont(font)
        self.oD.setObjectName("oD")
        self.oN2 = QtWidgets.QLineEdit(parent=self.groupBox_5)
        self.oN2.setGeometry(QtCore.QRect(230, 110, 131, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oN2.setFont(font)
        self.oN2.setObjectName("oN2")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(50, 50, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(50, 110, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.nutTaokhoa1 = QtWidgets.QPushButton(parent=self.groupBox)
        self.nutTaokhoa1.setGeometry(QtCore.QRect(320, 580, 141, 51))
        self.nutTaokhoa1.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutTaokhoa1.setObjectName("nutTaokhoa1")
        self.nutThoat1 = QtWidgets.QPushButton(parent=self.groupBox)
        self.nutThoat1.setGeometry(QtCore.QRect(560, 580, 141, 51))
        self.nutThoat1.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 14pt \"Times New Roman\";")
        self.nutThoat1.setObjectName("nutThoat1")
        self.oSoNgtoP = QtWidgets.QLineEdit(parent=self.groupBox)
        self.oSoNgtoP.setGeometry(QtCore.QRect(110, 51, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oSoNgtoP.setFont(font)
        self.oSoNgtoP.setObjectName("oSoNgtoP")
        self.oSoNgtoQ = QtWidgets.QLineEdit(parent=self.groupBox)
        self.oSoNgtoQ.setGeometry(QtCore.QRect(110, 110, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oSoNgtoQ.setFont(font)
        self.oSoNgtoQ.setObjectName("oSoNgtoQ")
        self.label_15 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_15.setGeometry(QtCore.QRect(370, 50, 55, 16))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_16.setGeometry(QtCore.QRect(360, 50, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_17.setGeometry(QtCore.QRect(360, 100, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_17.setObjectName("label_17")
        self.label_23 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_23.setGeometry(QtCore.QRect(800, 20, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_24.setGeometry(QtCore.QRect(830, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_24.setObjectName("label_24")
        self.tabWidget.addTab(self.taoKhoa, "")
        self.KyVanBan = QtWidgets.QWidget()
        self.KyVanBan.setObjectName("KyVanBan")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.KyVanBan)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 20, 1111, 661))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(40, 300, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(40, 430, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.nutTaivanban = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.nutTaivanban.setGeometry(QtCore.QRect(120, 590, 141, 51))
        self.nutTaivanban.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutTaivanban.setObjectName("nutTaivanban")
        self.NutKy = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.NutKy.setGeometry(QtCore.QRect(350, 590, 141, 51))
        self.NutKy.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.NutKy.setObjectName("NutKy")
        self.nutLuuChuKy = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.nutLuuChuKy.setGeometry(QtCore.QRect(590, 590, 141, 51))
        self.nutLuuChuKy.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutLuuChuKy.setObjectName("nutLuuChuKy")
        self.nutThoat = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.nutThoat.setGeometry(QtCore.QRect(810, 590, 141, 51))
        self.nutThoat.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutThoat.setObjectName("nutThoat")
        self.oVanBanCanKy = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.oVanBanCanKy.setGeometry(QtCore.QRect(213, 36, 831, 241))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oVanBanCanKy.setFont(font)
        self.oVanBanCanKy.setObjectName("oVanBanCanKy")
        self.oHamBam = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.oHamBam.setGeometry(QtCore.QRect(210, 296, 831, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oHamBam.setFont(font)
        self.oHamBam.setObjectName("oHamBam")
        self.oChuKy = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.oChuKy.setGeometry(QtCore.QRect(210, 420, 831, 81))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oChuKy.setFont(font)
        self.oChuKy.setObjectName("oChuKy")
        self.label_18 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(1050, 40, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_18.setObjectName("label_18")
        self.tabWidget.addTab(self.KyVanBan, "")
        self.XNchuKy = QtWidgets.QWidget()
        self.XNchuKy.setObjectName("XNchuKy")
        self.groupBox_6 = QtWidgets.QGroupBox(parent=self.XNchuKy)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 1101, 661))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_10.setGeometry(QtCore.QRect(10, 100, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_11.setGeometry(QtCore.QRect(10, 330, 161, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_12.setGeometry(QtCore.QRect(10, 490, 131, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.nutTaiVanBan2 = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.nutTaiVanBan2.setGeometry(QtCore.QRect(110, 590, 141, 51))
        self.nutTaiVanBan2.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutTaiVanBan2.setObjectName("nutTaiVanBan2")
        self.nutTaiChuKy = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.nutTaiChuKy.setGeometry(QtCore.QRect(340, 590, 141, 51))
        self.nutTaiChuKy.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutTaiChuKy.setObjectName("nutTaiChuKy")
        self.nutXacNhan = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.nutXacNhan.setGeometry(QtCore.QRect(570, 590, 141, 51))
        self.nutXacNhan.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutXacNhan.setObjectName("nutXacNhan")
        self.nutThoat3 = QtWidgets.QPushButton(parent=self.groupBox_6)
        self.nutThoat3.setGeometry(QtCore.QRect(800, 590, 141, 51))
        self.nutThoat3.setStyleSheet("background-color:rgb(166, 220, 255);\n"
"font: 75 14pt \"Times New Roman\";")
        self.nutThoat3.setObjectName("nutThoat3")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_13.setGeometry(QtCore.QRect(210, 480, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_14.setGeometry(QtCore.QRect(490, 480, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.oE2 = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.oE2.setGeometry(QtCore.QRect(250, 470, 181, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oE2.setFont(font)
        self.oE2.setText("")
        self.oE2.setObjectName("oE2")
        self.oN3 = QtWidgets.QLineEdit(parent=self.groupBox_6)
        self.oN3.setGeometry(QtCore.QRect(540, 470, 201, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oN3.setFont(font)
        self.oN3.setObjectName("oN3")
        self.oVanBanCanXN = QtWidgets.QPlainTextEdit(parent=self.groupBox_6)
        self.oVanBanCanXN.setGeometry(QtCore.QRect(210, 30, 821, 221))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oVanBanCanXN.setFont(font)
        self.oVanBanCanXN.setObjectName("oVanBanCanXN")
        self.oXNchuKy = QtWidgets.QPlainTextEdit(parent=self.groupBox_6)
        self.oXNchuKy.setGeometry(QtCore.QRect(210, 310, 821, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.oXNchuKy.setFont(font)
        self.oXNchuKy.setObjectName("oXNchuKy")
        self.label_19 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(1040, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(1040, 290, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(440, 460, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(parent=self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(750, 450, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("color:rgb(255, 29, 32)")
        self.label_22.setObjectName("label_22")
        self.Vanbandaky = QtWidgets.QRadioButton(parent=self.groupBox_6)
        self.Vanbandaky.setGeometry(QtCore.QRect(20, 180, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Vanbandaky.setFont(font)
        self.Vanbandaky.setObjectName("Vanbandaky")
        self.Vanbangoc = QtWidgets.QRadioButton(parent=self.groupBox_6)
        self.Vanbangoc.setGeometry(QtCore.QRect(20, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(9)
        self.Vanbangoc.setFont(font)
        self.Vanbangoc.setObjectName("Vanbangoc")
        self.tabWidget.addTab(self.XNchuKy, "")
        self.HuongDan = QtWidgets.QWidget()
        self.HuongDan.setObjectName("HuongDan")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.HuongDan)
        self.textBrowser.setGeometry(QtCore.QRect(10, 30, 1111, 551))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.textBrowser.setFont(font)
        self.textBrowser.setObjectName("textBrowser")
        self.tabWidget.addTab(self.HuongDan, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setLocale(QtCore.QLocale(QtCore.QLocale.Language.Vietnamese, QtCore.QLocale.Country.Vietnam))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Phần mềm Chữ ký điện tử RSA"))
        self.groupBox.setTitle(_translate("MainWindow", "Chọn số nguyên tố"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Tính các giá trị"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Khóa công khai"))
        self.label_3.setText(_translate("MainWindow", "E"))
        self.label_4.setText(_translate("MainWindow", "N"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Khóa bí mật"))
        self.label_5.setText(_translate("MainWindow", "D"))
        self.label_6.setText(_translate("MainWindow", "N"))
        self.label.setText(_translate("MainWindow", "P"))
        self.label_2.setText(_translate("MainWindow", "Q"))
        self.nutTaokhoa1.setText(_translate("MainWindow", "Tạo khóa"))
        self.nutThoat1.setText(_translate("MainWindow", "Thoát"))
        self.label_16.setText(_translate("MainWindow", "(*)"))
        self.label_17.setText(_translate("MainWindow", "(*)"))
        self.label_23.setText(_translate("MainWindow", "(*)"))
        self.label_24.setText(_translate("MainWindow", ": Không được để trống"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.taoKhoa), _translate("MainWindow", "Tạo khóa"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Ký"))
        self.label_7.setText(_translate("MainWindow", "Văn bản cần ký"))
        self.label_8.setText(_translate("MainWindow", "Hàm băm"))
        self.label_9.setText(_translate("MainWindow", "Chữ ký"))
        self.nutTaivanban.setText(_translate("MainWindow", "Tải văn bản"))
        self.NutKy.setText(_translate("MainWindow", "Ký"))
        self.nutLuuChuKy.setText(_translate("MainWindow", "Lưu chữ ký"))
        self.nutThoat.setText(_translate("MainWindow", "Thoát"))
        self.label_18.setText(_translate("MainWindow", "(*)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.KyVanBan), _translate("MainWindow", "Ký văn bản"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Xác nhận"))
        self.label_10.setText(_translate("MainWindow", "Văn bản cần xác nhận"))
        self.label_11.setText(_translate("MainWindow", "Xác nhận chữ ký"))
        self.label_12.setText(_translate("MainWindow", "Nhập xác nhận"))
        self.nutTaiVanBan2.setText(_translate("MainWindow", "Tải văn bản"))
        self.nutTaiChuKy.setText(_translate("MainWindow", "Tải chữ ký"))
        self.nutXacNhan.setText(_translate("MainWindow", "Xác nhận"))
        self.nutThoat3.setText(_translate("MainWindow", "Thoát"))
        self.label_13.setText(_translate("MainWindow", "E"))
        self.label_14.setText(_translate("MainWindow", "N"))
        self.label_19.setText(_translate("MainWindow", "(*)"))
        self.label_20.setText(_translate("MainWindow", "(*)"))
        self.label_21.setText(_translate("MainWindow", "(*)"))
        self.label_22.setText(_translate("MainWindow", "(*)"))
        self.Vanbandaky.setText(_translate("MainWindow", "Văn bản đã được ký"))
        self.Vanbangoc.setText(_translate("MainWindow", "Văn bản gốc (chưa ký)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.XNchuKy), _translate("MainWindow", "Xác nhận chữ ký"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Phần mềm chữ ký điện tử RSA lập trình bằng ngôn ngữ Python.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Thuật toán mã hóa </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Sha-256</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> để tạo hàm băm</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; text-decoration: underline;\">Chú ý bước xác nhận chữ ký:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">[*] Người dùng phải chọn một trong hai loại văn bản &quot;đã được ký&quot; hoặc &quot; văn bản gốc&quot;.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">[*] Trường hợp muốn kiểm tra </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Văn bản đã ký: </span><span style=\" font-family:\'MS Shell Dlg 2\';\">là văn bản phải có </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">chữ ký </span><span style=\" font-family:\'MS Shell Dlg 2\';\">(dòng đầu)</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\"> </span><span style=\" font-family:\'MS Shell Dlg 2\';\">và</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\"> khóa công khai </span><span style=\" font-family:\'MS Shell Dlg 2\';\">(dòng thứ hai) ở đầu của văn bản, người dùng chọn ô </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Văn bản đã được ký</span><span style=\" font-family:\'MS Shell Dlg 2\';\">, trường hợp muốn thẩm định trực tiếp bằng </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">văn bản gốc</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> , người dùng chọn ô </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Văn bản gốc .</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">[*] Nếu </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">văn bản đã được ký</span><span style=\" font-family:\'MS Shell Dlg 2\';\"> bằng phần mềm khác hãy sửa lại theo đúng định đạng văn bản sau đây:</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Dòng</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">| </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">1.    </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Chứa chuỗi chữ ký        </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">|</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\"> 2.     </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Chứa chuỗi khóa công khai    </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">|</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\"> 3.     </span><span style=\" font-family:\'MS Shell Dlg 2\';\">Văn bản gốc trở đi        </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">|</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\"> ...    ...                </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Em xin cảm ơn sự hướng dẫn của giảng viên: </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-weight:600;\">Ths.Trần Phương Nhung.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Tài liệu tham khảo và hướng dẫn: https://drive.google.com/file/d/1O53NFjAe31iXj3_67qDjgwg57ieicWTO/view</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Author: Tàng Trọng Phi</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Email:ztangphi360z@gmail.com</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.HuongDan), _translate("MainWindow", "Hướng dẫn"))
        self.nutThoat1.clicked.connect(QtCore.QCoreApplication.quit)
        self.nutThoat.clicked.connect(QtCore.QCoreApplication.quit)
        self.nutThoat3.clicked.connect(QtCore.QCoreApplication.quit)
        self.nutTaokhoa1.clicked.connect(self.createKey)
        self.nutTaivanban.clicked.connect(self.taivanban1)
        self.nutTaiVanBan2.clicked.connect(self.taivanban2)
        self.nutTaiChuKy.clicked.connect(self.taichuky)
        self.NutKy.clicked.connect(self.ky)
        self.nutLuuChuKy.clicked.connect(self.luuChuKy)
        self.nutXacNhan.clicked.connect(self.XacNhanCK)

        # Chọn file văn bản tải lên
    def taivanban1(self):
        f = QtWidgets.QFileDialog.getOpenFileName(caption='Select file', filter='File văn bản dạng *.txt',
                                                  directory='C:\\')
        if f[0] == '' or f[1] == '':
            return 1
        file = open(f[0], 'r', encoding='utf-8')
        self.oVanBanCanKy.setPlainText(file.read())
        file.close()

    def taivanban2(self):
        f = QtWidgets.QFileDialog.getOpenFileName(caption='Select file', filter='File văn bản dạng *.txt',
                                                  directory='C:\\')
        if f[0] == '' or f[1] == '':
            return 1
        file = open(f[0], 'r', encoding='utf-8')
        self.oVanBanCanXN.setPlainText(file.read())
        file.close()

    def taichuky(self):
        f = QtWidgets.QFileDialog.getOpenFileName(caption='Select file', filter='File chữ ký dạng *.txt',
                                                  directory='C:\\')
        if f[0] == '' or f[1] == '':
            return 1
        file = open(f[0], 'r', encoding='utf-8')
        self.oXNchuKy.setPlainText(file.read())
        file.close()

        # Tạo khóa

    checkStatus = False  # Tôi code tôi khác tự phải biết =)) @Phideptrai

    def createKey(self):
        # Xử lý đầu vào không phải số nguyên tố
        def isPrime(a):
            if a < 2 or (a > 2 and a % 2 == 0):
                return 0
            elif a == 2 or a == 3 or a == 5:
                return 1
            else:
                for i in range(3, a // 2 + 1, 2):
                    if a % i == 0:
                        return 0
                        break
                    else:
                        return 1

        # Thuật toán Euclid tìm UCLN
        def gcd(x, y):
            if x == 0 and y == 0:
                return 0
            elif x == 0:
                return y
            elif y == 0:
                return x
            elif x == 1 or y == 1:
                return 1
            else:
                if y > x:
                    x, y = y, x
                r = 0
                while True:
                    r = x % y
                    x, y = y, r
                    if r == 0:
                        return x
                        break

        # Tìm key public và key private, xử lý đầu vào P và Q
        try:
            P = int(self.oSoNgtoP.text())
            Q = int(self.oSoNgtoQ.text())
            if isPrime(P) != 1 or isPrime(Q) != 1:
                messagebox.showwarning("Chú ý", "Số bạn nhập không phải là số nguyên tố, hãy thử lại!")
                return 1
        except ValueError:
            messagebox.showerror("Lỗi đầu vào", "Ký tự không hợp lệ, thử lại sau!")
            return 1
        n = P * Q
        FiN = (P - 1) * (Q - 1)
        while True:
            b = random.randint(2, FiN - 1)  # Lấy random b sao cho 1<b<FiN và khi thỏa mãn gcd(b,FiN)==1 thì thôi
            if gcd(b, FiN) == 1:
                break  # Ta có key public: Kpub = {b, n}

        r = [FiN, b]  # Tập số dư chạy từ r0
        q = []  # Tập thương chạy từ q0
        i = 0
        t = [0, 1]  # Tập t, vì ko cần tính S nên ko có S

        # Tính a = b^-1 mod FiN --> áp dụng thuật toán Euclid mở rộng
        while True:
            temp1 = r[i] % r[i + 1]  # Tính ri
            temp2 = r[i] // r[i + 1]  # Tính qi
            q.append(temp2)
            r.append(temp1)
            if i > 1:
                temp3 = t[i - 2] - q[i - 2] * t[i - 1]  # Tính ti (từ t2 trở đi)
                t.append(temp3)
            if temp1 == 0:  # Phần số dư cuối cùng bằng 0 sẽ chỉ có thêm 1 bước tính t nữa và thoát vòng lặp
                a = t[i - 1] - q[i - 1] * t[i]
                break
            i += 1
        if a < 0:
            a = a + FiN  # Tính lại a trên vành Z(FiN) nếu a < 0 như vậy có key private: Kpri = {a, p, q}

        self.oN1.setText(str(n))
        self.oN2.setText(str(n))
        self.oE1.setText(str(b))
        self.oD.setText(str(a))
        self.checkStatus = True

    # Tạo chữ ký RSA
    checkStatus2 = False

    def ky(self):
        if not self.checkStatus:
            messagebox.showwarning("Chú ý", "Bạn phải tạo khóa trước!")
            return 1
        VanBan = self.oVanBanCanKy.toPlainText()
        if VanBan == '':
            messagebox.showwarning("Chú ý", "Không được để trống văn bản!")
            return 1
        hamBam = hashlib.sha256(VanBan.encode())
        self.oHamBam.setPlainText(hamBam.hexdigest())
        test = list(self.oHamBam.toPlainText())
        # Chuyển hash ở dạng hex về decimal
        for i in range(len(test)):
            if test[i] == 'a':
                test[i] = '10'
            elif test[i] == 'b':
                test[i] = '11'
            elif test[i] == 'c':
                test[i] = '12'
            elif test[i] == 'd':
                test[i] = '13'
            elif test[i] == 'e':
                test[i] = '14'
            elif test[i] == 'f':
                test[i] = '15'
            test[i] = int(test[i])
        # Tạo chữ ký (Mã hóa hàm băm bằng khóa riêng tư RSA)
        # Thuật toán bình phương và nhân tính h^a mod n
        n = int(self.oD.text())  # Gán n trong thuật toán bằng a trong key private
        n = bin(n)
        n = n[2:]  # Chuyển n về chuỗi số nhị phân để tính số bước của thuật toán
        m = int(self.oN1.text())
        chuKy = []

        # Thuat toan binh phuong va nhan
        def encrypt(x):
            p = 1
            for j in range(len(n)):
                p = p * p
                p = p % m
                if n[j] == '1':  # Nếu bước i có b = 1 thì nhân thêm x
                    p = p * x
                    p = p % m
            return p

        # Mã hóa RSA từng phần tử của hàm băm
        for i in range(len(test)):
            chuKy.append(encrypt(test[i]))  # Từng phần tử của chữ ký

        chuKy2 = ''  # Chữ ký để hiện trong ô chữ ký trên ứng dụng
        for i in range(len(chuKy)):
            if i == len(chuKy) - 1:
                chuKy2 = chuKy2 + str(chuKy[i])
                break
            chuKy2 = chuKy2 + str(chuKy[i]) + '-'
        self.oChuKy.setPlainText(chuKy2)
        # Tạo 1 file riêng, copy văn bản cần kí và thêm chữ ký ở đầu để đảm bảo bản gốc cho người dùng
        f = QtWidgets.QFileDialog.getSaveFileName(caption='Lưu file văn bản đã ký', filter='*.txt',
                                                  directory='C:\\')
        if f[0] == '' or f[1] == '':
            return 1
        file = open(f[0], 'w', encoding='utf-8')
        file.write("Signature: " + self.oChuKy.toPlainText())
        file.write("\nPublic Key: {" + self.oE1.text() + ", " + self.oN1.text() + "}\n")
        file.write(self.oVanBanCanKy.toPlainText())
        file.close()
        self.checkStatus2 = True
        messagebox.showinfo(title="Thông báo", message="Ký văn bản thành công!\nĐường dẫn: " + f[0])

    #Lưu lại chữ ký số đã tạo vào file riêng
    def luuChuKy(self):
        if not self.checkStatus2:  # Kiểm tra quá trình ký, nếu chưa ký sẽ không lưu được chữ ký. Nghĩ mãi mới ra, đúng là Phi đẹp trai hehe
            messagebox.showwarning("Chú ý", "Bạn phải ký văn bản trước!")
            return 1
        f = QtWidgets.QFileDialog.getSaveFileName(caption='Lưu file cho chữ ký', filter='*.txt',
                                                  directory='C:\\')
        if f[0] == '' or f[1] == '':
            return 1
        file = open(f[0], 'w', encoding='utf-8')
        file.write(self.oChuKy.toPlainText())
        file.close()
        messagebox.showinfo("Thông báo", "Lưu chữ ký thành công!\nĐường dẫn: " + f[0])

    #Kiểm tra chữ ký và văn bản
    def XacNhanCK(self):
        # Xử lý input nào
        if (self.oVanBanCanXN == '' or self.oXNchuKy == '') or (self.oE2.text() == '' or self.oN3.text() == ''):
            messagebox.showwarning("Chú ý", "Không được để trống các trường bắt buộc!")
            return 1
        try:
            b = int(self.oE2.text())
            n = int(self.oN3.text())
        except ValueError:
            messagebox.showerror("Lỗi", "Vui lòng nhập các tham số E, N hợp lệ")
            return 1

        # Giải mã chữ kí ngược về hàm băm để so sánh
        # Xử lý đầu vào cho chữ ký
        try:
            ChuKy = self.oXNchuKy.toPlainText().split("-")
            for i in range(len(ChuKy)):
                ChuKy[i] = int(ChuKy[i]) # Đưa str về int để tính toán
        except ValueError:
            messagebox.showwarning("Chú ý", "Định dạng chữ ký không hợp lệ!")
            return 1
        # Thuat toan binh phuong va nhan tinh y^b mod n
        b = bin(b)
        b = b[2:] #Chuyển b về chuỗi số nhị phân để tính số bước của thuật toán
        def decrypt(y):
            p = 1
            for i in range(len(b)):
                p = p*p
                p = p%n
                if b[i] == '1':
                    p = p*y
                    p = p%n
            return p

        # Giải mã từng phần tử của chữ ký
        ChuKy2 = ''
        for i in range(len(ChuKy)):
            ChuKy[i] = decrypt(ChuKy[i])
        for i in range(len(ChuKy)):
            if ChuKy[i] == 10:
                ChuKy[i] = 'a'
            elif ChuKy[i] == 11:
                ChuKy[i] = 'b'
            elif ChuKy[i] == 12:
                ChuKy[i] = 'c'
            elif ChuKy[i] == 13:
                ChuKy[i] = 'd'
            elif ChuKy[i] == 14:
                ChuKy[i] = 'e'
            elif ChuKy[i] == 15:
                ChuKy[i] = 'f'
            ChuKy[i] = str(ChuKy[i])
        for i in range(len(ChuKy)):
            ChuKy2 += ChuKy[i] # Hoàn tất đưa chữ ký về lại hàm băm

        if not self.Vanbangoc.isChecked() and not self.Vanbandaky.isChecked():
            messagebox.showwarning("Chú ý", "Bạn chưa chọn loại văn bản!")
            return 1

        if self.Vanbangoc.isChecked(): #option văn bản gốc
            Vanban = self.oVanBanCanXN.toPlainText()
            h = hashlib.sha256(Vanban.encode())
            h = h.hexdigest()
            if h != ChuKy2:
                messagebox.showinfo("Thông báo", "Không khớp! Có thể là do:\n- Chọn sai loại văn bản(đã ký/gốc)\n- Văn bản đã được chỉnh sửa \n- Chữ ký không chính xác\n- Khóa công khai không chính xác ")
            else:
                messagebox.showinfo("Thông báo", "Chữ ký chính xác!")
        else: #option văn bản đã ký
            Vanban = self.oVanBanCanXN.toPlainText()
            file = open('C:\\Users\\Public\\0xF0FA7B.txt', 'w')
            file.write(Vanban)
            file.close()
            file = open('C:\\Users\\Public\\0xF0FA7B.txt', 'r+')
            file.readline()
            file.readline()
            Vanban = file.read()
            print(Vanban)
            file.close()
            os.remove('C:\\Users\Public\\0xF0FA7B.txt')
            h = hashlib.sha256(Vanban.encode())
            h = h.hexdigest()
            if h != ChuKy2:
                messagebox.showinfo("Thông báo", "Không khớp! Có thể là do:\n- Chọn sai loại văn bản(đã ký/gốc)\n- Văn bản đã được chỉnh sửa \n- Chữ ký không chính xác\n- Khóa công khai không chính xác")
            else:
                messagebox.showinfo("Thông báo", "Chữ ký chính xác!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
